"use client";

import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { Compass } from "lucide-react";
import { useAuth } from "@/lib/auth";
import {
  getAllTestSections,
  type TestSection,
} from "@/services/practiceTestService";
import {
  PageContainer,
  PageHeader,
  LoadingState,
  ErrorDisplay,
  CardGrid,
  EmptyState,
  SectionHeading,
} from "@/components/common/UIComponents";
import { Button } from "@/components/ui/button";
import { SectionCard } from "@/components/practice/SectionCard";
import { FullTestCard } from "@/components/practice/FullTestCard";
import { SignInGate, SignInGateIcons } from "@/components/auth/SignInGate";
import { logger } from "@/utils/logger";
import { env } from "@/config/env";
import { useTestMode } from "@/hooks/useTestMode";

const PracticeDebug = dynamic(() => import("./debug"), { ssr: false });

const HUB_DESCRIPTION =
  "Every question is generated by AI and tuned to your skill level. Start with a full-length test, or sharpen one section at a time.";

function HubHeader() {
  return (
    <PageHeader
      eyebrow="SAT Prep"
      title="Practice that adapts to you"
      description={HUB_DESCRIPTION}
    />
  );
}

function DebugPanel({
  showDebug,
  onToggle,
}: {
  showDebug: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="mb-6">
      <div className="text-right">
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={onToggle}
          aria-pressed={showDebug}
        >
          {showDebug ? "Hide debug info" : "Show debug info"}
        </Button>
      </div>
      {showDebug && <PracticeDebug />}
    </div>
  );
}

export default function PracticeClient({
  authIsGuaranteed = false,
  initialSections,
  testParam,
}: {
  authIsGuaranteed?: boolean;
  initialSections?: TestSection[];
  testParam?: string;
}) {
  const { user, isLoading: isAuthLoading } = useAuth();
  const hasInitialSections = Boolean(initialSections);
  const [sections, setSections] = useState<TestSection[]>(
    initialSections ?? []
  );
  const [loading, setLoading] = useState(!initialSections);
  const [error, setError] = useState<string | null>(null);
  const [showDebug, setShowDebug] = useState(env.debug);
  const isTestMode = useTestMode(testParam);
  const canPractice = Boolean(user) || isTestMode;
  const debugEnabled = env.debug;

  useEffect(() => {
    if (!user && !isTestMode) return;
    if (hasInitialSections) return;

    let isCancelled = false;
    setError(null);
    setLoading(true);

    getAllTestSections()
      .then((data) => {
        if (!isCancelled) setSections(data);
      })
      .catch((err) => {
        logger.error("Error fetching sections", err);
        setError(
          err instanceof Error
            ? err.message
            : "Failed to fetch practice test sections"
        );
      })
      .finally(() => {
        if (!isCancelled) setLoading(false);
      });

    return () => {
      isCancelled = true;
    };
  }, [hasInitialSections, user, isTestMode]);

  const debugPanel = debugEnabled ? (
    <DebugPanel
      showDebug={showDebug}
      onToggle={() => setShowDebug((prev) => !prev)}
    />
  ) : null;

  if (isAuthLoading && !isTestMode) {
    return (
      <PageContainer>
        <HubHeader />
        <LoadingState
          message={
            authIsGuaranteed ? "Loading SAT Prep..." : "Checking your session..."
          }
        />
      </PageContainer>
    );
  }

  if (!canPractice) {
    return (
      <PageContainer>
        <HubHeader />
        {debugPanel}
        <SignInGate
          title="Sign in to start SAT Prep"
          description={
            authIsGuaranteed
              ? "Your session expired. Sign in again to access practice tests."
              : "Our AI-powered practice tests are personalized to your skill level and help you improve gradually."
          }
          icon={SignInGateIcons.practice}
        />
      </PageContainer>
    );
  }

  return (
    <PageContainer>
      <HubHeader />
      {debugPanel}

      <FullTestCard />

      <SectionHeading title="Practice by section" icon={<Compass />} />

      {error && <ErrorDisplay message={error} />}

      {!error && loading && <LoadingState message="Loading sections..." />}

      {!error && !loading && sections.length === 0 && (
        <EmptyState
          icon={<Compass />}
          title="No sections yet"
          message="Practice sections aren't available right now. Please check back soon."
        />
      )}

      {!error && !loading && sections.length > 0 && (
        <CardGrid columns={{ default: 1, md: 2, lg: 4 }}>
          {sections.map((section) => (
            <SectionCard key={section.id} section={section} />
          ))}
        </CardGrid>
      )}
    </PageContainer>
  );
}
